import TreeNode from "../treeNode/treeNode";
import constructTreeProof from "./constructTreeProof";

describe("constructTreeProof", () => {
  it("test 1", () => {
    const expected = {
      absurdity: false,
      branchingWff: true,
      data: ["t", "->", "s"],
      left: null,
      middle: {
        absurdity: false,
        branchingWff: true,
        data: ["q", "->", "y"],
        left: null,
        middle: {
          absurdity: false,
          branchingWff: false,
          data: ["~", "(", "p", "->", "r", ")"],
          left: null,
          middle: {
            absurdity: false,
            branchingWff: false,
            data: ["p"],
            left: null,
            middle: {
              absurdity: false,
              branchingWff: false,
              data: ["~r"],
              left: {
                absurdity: false,
                branchingWff: false,
                data: ["~t"],
                left: {
                  absurdity: false,
                  branchingWff: false,
                  data: ["~q"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                middle: null,
                orderNumber: 6,
                originNumber: 1,
                primitive: true,
                right: {
                  absurdity: false,
                  branchingWff: false,
                  data: ["y"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                unpacked: false,
              },
              middle: null,
              orderNumber: 5,
              originNumber: 3,
              primitive: true,
              right: {
                absurdity: false,
                branchingWff: false,
                data: ["s"],
                left: {
                  absurdity: false,
                  branchingWff: false,
                  data: ["~q"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                middle: null,
                orderNumber: 6,
                originNumber: 1,
                primitive: true,
                right: {
                  absurdity: false,
                  branchingWff: false,
                  data: ["y"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                unpacked: false,
              },
              unpacked: false,
            },
            orderNumber: 4,
            originNumber: 3,
            primitive: true,
            right: null,
            unpacked: false,
          },
          orderNumber: 3,
          originNumber: null,
          primitive: false,
          right: null,
          unpacked: true,
        },
        orderNumber: 2,
        originNumber: null,
        primitive: false,
        right: null,
        unpacked: true,
      },
      orderNumber: 1,
      originNumber: null,
      primitive: false,
      right: null,
      unpacked: true,
    };

    expect(constructTreeProof(["t -> s", "q -> y"], "p -> r")).toEqual(
      expected
    );
  });

  it("test 2", () => {
    const expected = {
      absurdity: false,
      branchingWff: true,
      data: ["p", "->", "q"],
      left: null,
      middle: {
        absurdity: false,
        branchingWff: true,
        data: ["q", "->", "r"],
        left: null,
        middle: {
          absurdity: false,
          branchingWff: false,
          data: ["~", "(", "p", "->", "r", ")"],
          left: null,
          middle: {
            absurdity: false,
            branchingWff: false,
            data: ["p"],
            left: null,
            middle: {
              absurdity: false,
              branchingWff: false,
              data: ["~r"],
              left: {
                absurdity: true,
                branchingWff: false,
                data: ["~p"],
                left: null,
                middle: null,
                orderNumber: 6,
                originNumber: 1,
                primitive: true,
                right: null,
                unpacked: false,
              },
              middle: null,
              orderNumber: 5,
              originNumber: 3,
              primitive: true,
              right: {
                absurdity: false,
                branchingWff: false,
                data: ["q"],
                left: {
                  absurdity: true,
                  branchingWff: false,
                  data: ["~q"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                middle: null,
                orderNumber: 6,
                originNumber: 1,
                primitive: true,
                right: {
                  absurdity: true,
                  branchingWff: false,
                  data: ["r"],
                  left: null,
                  middle: null,
                  orderNumber: 7,
                  originNumber: 2,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                unpacked: false,
              },
              unpacked: false,
            },
            orderNumber: 4,
            originNumber: 3,
            primitive: true,
            right: null,
            unpacked: false,
          },
          orderNumber: 3,
          originNumber: null,
          primitive: false,
          right: null,
          unpacked: true,
        },
        orderNumber: 2,
        originNumber: null,
        primitive: false,
        right: null,
        unpacked: true,
      },
      orderNumber: 1,
      originNumber: null,
      primitive: false,
      right: null,
      unpacked: true,
    };

    expect(constructTreeProof(["p -> q", "q -> r"], "p -> r")).toEqual(
      expected
    );
  });

  /**
   * FAILS DUE TO INCORRECT TYPE ASSERTION
   */
  it("test 3", () => {
    const expected = {
      absurdity: false,
      branchingWff: true,
      data: ["(", "p", "&", "q", ")", "->", "r"],
      left: null,
      middle: {
        absurdity: false,
        branchingWff: false,
        data: [
          "~",
          "(",
          "(",
          "p",
          "->",
          "r",
          ")",
          "|",
          "(",
          "q",
          "->",
          "r",
          ")",
        ],
        left: null,
        middle: {
          absurdity: false,
          branchingWff: false,
          data: ["~", "(", "p", "->", "r", ")"],
          left: null,
          middle: {
            absurdity: false,
            branchingWff: false,
            data: ["~", "(", "q", "->", "r", ")"],
            left: null,
            middle: {
              absurdity: false,
              branchingWff: false,
              data: ["p"],
              left: null,
              middle: {
                absurdity: false,
                branchingWff: false,
                data: ["~r"],
                left: null,
                middle: {
                  absurdity: false,
                  branchingWff: false,
                  data: ["q"],
                  left: null,
                  middle: {
                    absurdity: false,
                    branchingWff: false,
                    data: ["~r"],
                    left: {
                      absurdity: false,
                      branchingWff: false,
                      data: ["~", "(", "p", "&", "q", ")"],
                      left: {
                        absurdity: true,
                        branchingWff: false,
                        data: ["~p"],
                        left: null,
                        middle: null,
                        orderNumber: 10,
                        originNumber: 9,
                        primitive: true,
                        right: null,
                        unpacked: false,
                      },
                      middle: null,
                      orderNumber: 9,
                      originNumber: 1,
                      primitive: false,
                      right: {
                        absurdity: true,
                        branchingWff: false,
                        data: ["~q"],
                        left: null,
                        middle: null,
                        orderNumber: 10,
                        originNumber: 9,
                        primitive: true,
                        right: null,
                        unpacked: false,
                      },
                      unpacked: true,
                    },
                    middle: null,
                    orderNumber: 8,
                    originNumber: 4,
                    primitive: true,
                    right: {
                      absurdity: true,
                      branchingWff: false,
                      data: ["r"],
                      left: null,
                      middle: null,
                      orderNumber: 9,
                      originNumber: 1,
                      primitive: true,
                      right: null,
                      unpacked: false,
                    },
                    unpacked: false,
                  },
                  orderNumber: 7,
                  originNumber: 4,
                  primitive: true,
                  right: null,
                  unpacked: false,
                },
                orderNumber: 6,
                originNumber: 3,
                primitive: true,
                right: null,
                unpacked: false,
              },
              orderNumber: 5,
              originNumber: 3,
              primitive: true,
              right: null,
              unpacked: false,
            },
            orderNumber: 4,
            originNumber: 2,
            primitive: false,
            right: null,
            unpacked: true,
          },
          orderNumber: 3,
          originNumber: 2,
          primitive: false,
          right: null,
          unpacked: true,
        },
        orderNumber: 2,
        originNumber: null,
        primitive: false,
        right: null,
        unpacked: true,
      },
      orderNumber: 1,
      originNumber: null,
      primitive: false,
      right: null,
      unpacked: true,
    };

    expect(
      constructTreeProof(["( p & q ) -> r"], "(p -> r) | ( q -> r )")
    ).toEqual(expected);
  });
  it("test 4 --destructuring test 3", () => {
    const expected = {
      absurdity: false,
      branchingWff: true,
      data: ["(", "p", "&", "q", ")", "->", "r"],
      left: null,
      middle: {
        absurdity: false,
        branchingWff: false,
        data: ["~", "(", "p", "->", "r", ")"],
        left: null,
        middle: {
          absurdity: false,
          branchingWff: false,
          data: ["p"],
          left: null,
          middle: {
            absurdity: false,
            branchingWff: false,
            data: ["~r"],
            left: {
              absurdity: false,
              branchingWff: false,
              data: ["~", "(", "p", "&", "q", ")"],
              left: {
                absurdity: true,
                branchingWff: false,
                data: ["~p"],
                left: null,
                middle: null,
                orderNumber: 6,
                originNumber: 5,
                primitive: true,
                right: null,
                unpacked: false,
              },
              middle: null,
              orderNumber: 5,
              originNumber: 1,
              primitive: false,
              right: {
                absurdity: false,
                branchingWff: false,
                data: ["~q"],
                left: null,
                middle: null,
                orderNumber: 6,
                originNumber: 5,
                primitive: true,
                right: null,
                unpacked: false,
              },
              unpacked: true,
            },
            middle: null,
            orderNumber: 4,
            originNumber: 2,
            primitive: true,
            right: {
              absurdity: true,
              branchingWff: false,
              data: ["r"],
              left: null,
              middle: null,
              orderNumber: 5,
              originNumber: 1,
              primitive: true,
              right: null,
              unpacked: false,
            },
            unpacked: false,
          },
          orderNumber: 3,
          originNumber: 2,
          primitive: true,
          right: null,
          unpacked: false,
        },
        orderNumber: 2,
        originNumber: null,
        primitive: false,
        right: null,
        unpacked: true,
      },
      orderNumber: 1,
      originNumber: null,
      primitive: false,
      right: null,
      unpacked: true,
    };

    expect(constructTreeProof(["( p & q ) -> r"], "p -> r")).toEqual(expected);
  });

  /**
   *  TEST FOR VALIDITY
   *  BY CHANGING THE RETURN VALUE
   *  FOR NOW
   */
  it.skip("test validity", () => {
    const expected = true;

    expect(
      constructTreeProof(["(p | (q & r))"], "((p | q) & (p | r))")
    ).toEqual(expected);
  });
});

export {};
